spring.application.name=ziwei-doushu
server.port=8080

# 保证中文 JSON 正常输出
spring.jackson.default-property-inclusion=non_null
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
